apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nominatim.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.nominatim.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.nominatim.persistence.size | default "50Gi" }}
  accessModes:
    - {{ .Values.nominatim.persistence.accessMode | default "ReadWriteOnce" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nominatim.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nominatim.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.postgres.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | default "100Gi" }}
  accessModes:
    - {{ .Values.postgres.persistence.accessMode | default "ReadWriteOnce" }}
