apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "nominatim-api.labels" . | nindent 4 }}
spec:
  {{- with .Values.strategy }}
  strategy: 
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nominatim-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nominatim-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Chart.Name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: nominatim-init
          securityContext:
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          image: "{{ .Values.init.image.repository }}:{{ .Chart.AppVersion }}-{{ .Values.init.image.tag }}"
          imagePullPolicy: {{ .Values.init.image.pullPolicy }}
          env:
            - name: NOMINATIM_PBF
              value: {{ .Values.init.pbf_url }}
          volumeMounts:
            - name: {{ .Chart.Name }}
              mountPath: /data
          resources:
            {{- toYaml .Values.init.resources | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}-{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: {{ .Chart.Name }}
              mountPath: /data
          env:
            - name: NOMINATIM_DATASE_HOST
              value: nominatim-db.nominatim.svc.cluster.local
            - name: NOMINATIM_REQUEST_TIMEOUT
              value: "60"
            - name: NOMINATIM_QUERY_TIMEOUT
              value: "60"
            - name: NOMINATIM_DATABASE_DSN
              value: pgsql:host=nominatim-db.nominatim.svc.cluster.local;port=5432;user=nominatim;password=nominatim;dbname=nominatim
            - name: NOMINATIM_VERSION
              value: {{ .Chart.AppVersion }}
            - name: POSTGRES_DB
              value: nominatim
            - name: NOMINATIM_IMPORT_STYLE
              value: {{ .Values.import_style | default "address" }}
            - name: NOMINATIM_REPLICATION_URL
              value: "{{ .Values.replication.url }}"
            - name: NOMINATIM_REPLICATION_UPDATE_INTERVAL
              value: "{{ .Values.replication.update_interval }}"
            - name: NOMINATIM_REPLICATION_RECHECK_INTERVAL
              value: "{{ .Values.replication.recheck_interval }}"
          readinessProbe:
            httpGet:
              path: /status?format=json
              port: http
          volumeMounts:
            - name: {{ .Chart.Name }}
              mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Chart.Name }}
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}