apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nominatim-api.selectorLabels" . | nindent 8 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "50Gi" }}
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}