init:
  image:
    repository: vit0r/postgres-init
    pullPolicy: IfNotPresent
    tag: 68
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
replicaCount: 1
image:
  repository: vit0r/postgres
  pullPolicy: IfNotPresent
  tag: 68
imagePullSecrets: []
podAnnotations: {}
persistence:
  storageClassName: standard
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 101
service:
  type: ClusterIP
  port: 5432
resources:
  requests:
    cpu: 2
    memory: 2Gi
  limits:
    cpu: 4
    memory: 8Gi
serviceAccount:
  create: true
  annotations: {}
  name: "nominatim-db"
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
strategy:
  type: Recreate
