apiVersion: v2
name: nominatim-api
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "4.5.0"
dependencies:
  - name: https://github.com/vit0r/nominatim/charts/nominatim-db
