init:
  image:
    repository: vit0r/nominatim-init
    pullPolicy: IfNotPresent
    tag: 66
  pbf_url: https://download.geofabrik.de/south-america/brazil-latest.osm.pbf
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
replicaCount: 1
image:
  repository: vit0r/nominatim
  pullPolicy: IfNotPresent
  tag: 66
replication:
  url: https://download.geofabrik.de/south-america/brazil-updates
  update_interval: "86400"
  recheck_interval: "900"
serviceAccount:
  create: true
  annotations: {}
  name: "nominatim-api"
podAnnotations: {}
securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1001
podSecurityContext: {}
persistence:
  storageClassName: standard
service:
  type: ClusterIP
  port: 8000
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: nominatim.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: nominatim-tls
  #    hosts:
  #      - nominatim.local
resources:
  requests:
    cpu: 2
    memory: 2Gi
  limits:
    cpu: 2
    memory: 4Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
nameOverride: "nominatim"
fullnameOverride: "nominatim"
strategy:
  type: Recreate
